/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CorrelationRouteImport } from './routes/correlation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ScenariosRouteImport } from './routes/scenarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationRoute = CorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/architecture': typeof ArchitectureRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/compliance': typeof ComplianceRoute
  '/correlation': typeof CorrelationRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/financial': typeof FinancialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pipeline': typeof PipelineRoute
  '/recommendations': typeof RecommendationsRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/architecture': typeof ArchitectureRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/compliance': typeof ComplianceRoute
  '/correlation': typeof CorrelationRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/financial': typeof FinancialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pipeline': typeof PipelineRoute
  '/recommendations': typeof RecommendationsRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/architecture': typeof ArchitectureRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/compliance': typeof ComplianceRoute
  '/correlation': typeof CorrelationRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/financial': typeof FinancialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pipeline': typeof PipelineRoute
  '/recommendations': typeof RecommendationsRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/architecture'
    | '/assets'
    | '/budget'
    | '/compliance'
    | '/correlation'
    | '/dashboard'
    | '/drivers'
    | '/financial'
    | '/how-it-works'
    | '/pipeline'
    | '/recommendations'
    | '/scenarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/architecture'
    | '/assets'
    | '/budget'
    | '/compliance'
    | '/correlation'
    | '/dashboard'
    | '/drivers'
    | '/financial'
    | '/how-it-works'
    | '/pipeline'
    | '/recommendations'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/architecture'
    | '/assets'
    | '/budget'
    | '/compliance'
    | '/correlation'
    | '/dashboard'
    | '/drivers'
    | '/financial'
    | '/how-it-works'
    | '/pipeline'
    | '/recommendations'
    | '/scenarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssetsRoute: typeof AssetsRoute
  BudgetRoute: typeof BudgetRoute
  ComplianceRoute: typeof ComplianceRoute
  CorrelationRoute: typeof CorrelationRoute
  DashboardRoute: typeof DashboardRoute
  DriversRoute: typeof DriversRoute
  FinancialRoute: typeof FinancialRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PipelineRoute: typeof PipelineRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ScenariosRoute: typeof ScenariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlation': {
      id: '/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof CorrelationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssetsRoute: AssetsRoute,
  BudgetRoute: BudgetRoute,
  ComplianceRoute: ComplianceRoute,
  CorrelationRoute: CorrelationRoute,
  DashboardRoute: DashboardRoute,
  DriversRoute: DriversRoute,
  FinancialRoute: FinancialRoute,
  HowItWorksRoute: HowItWorksRoute,
  PipelineRoute: PipelineRoute,
  RecommendationsRoute: RecommendationsRoute,
  ScenariosRoute: ScenariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
